export const siteConfig = {
  name: "Michael Boutin",
  handle: "imick.io",
  role: "AI Product Engineer",
  tagline: "Senior full-stack engineer shipping AI-native products end-to-end.",
  bio: "I'm a senior full-stack engineer who designs and builds AI-native products end-to-end: UI craft, frontend, and the backend integration that make AI features feel reliable in production. Recently shipped product UI for Takeup, an AI pricing platform for hotels and B&Bs, connecting Next.js and Server Actions to the AI services behind it.",
  description: "Senior full-stack engineer designing and shipping AI-native products end-to-end.",
  url: "https://imick.io",
  contactEmail: "michael@concreo.io",
  githubSponsorsUrl: "https://github.com/sponsors/PLACEHOLDER",
  repoUrl: "https://github.com/mboutin-toptal/imick-io",
  repoBranch: "main",
  newsletterArchiveUrl: "https://imick.beehiiv.com",
  newsletterSubscriberMilestone: 0,
} as const
